"""Add src_profile in user

Revision ID: 2f445e1603a3
Revises: 6c00034207c8
Create Date: 2024-11-08 21:04:38.810109
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f445e1603a3'
down_revision: Union[str, None] = '6c00034207c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('src_profile', sa.String(), nullable=True)
    )
    op.create_unique_constraint(None, 'users', ['src_profile'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'src_profile')
    # ### end Alembic commands ###
