"""Modify to declarative mode sqlalchemy

Revision ID: 6c00034207c8
Revises: 80c007348819
Create Date: 2024-10-07 13:52:53.703812
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c00034207c8'
down_revision: Union[str, None] = '80c007348819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'band_kibon_donjak',
        sa.Column('band_id', sa.UUID(), nullable=False),
        sa.Column('kibon_donjak_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_for', sa.UUID(), nullable=True),
        sa.Column('updated_for', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['kibon_donjak_id'], ['kibon_donjaks.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('band_id', 'kibon_donjak_id', 'id'),
    )
    op.add_column('band_kick', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column(
        'band_kick', sa.Column('created_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'band_kick', sa.Column('updated_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'band_kick', sa.Column('created_for', sa.UUID(), nullable=True)
    )
    op.add_column(
        'band_kick', sa.Column('updated_for', sa.UUID(), nullable=True)
    )
    op.add_column('band_poomsae', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column(
        'band_poomsae', sa.Column('created_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'band_poomsae', sa.Column('updated_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'band_poomsae', sa.Column('created_for', sa.UUID(), nullable=True)
    )
    op.add_column(
        'band_poomsae', sa.Column('updated_for', sa.UUID(), nullable=True)
    )
    op.alter_column(
        'bands', 'created_for', existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        'bands', 'updated_for', existing_type=sa.UUID(), nullable=True
    )
    op.drop_index('idx_created_updated_at', table_name='bands')
    op.drop_index('idx_created_updated_for', table_name='bands')
    op.drop_index('idx_gub', table_name='bands')
    op.alter_column(
        'kibon_donjaks',
        'description',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=600),
        existing_nullable=False,
    )
    op.alter_column(
        'kibon_donjaks', 'created_for', existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        'kibon_donjaks', 'updated_for', existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        'kicks', 'created_for', existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        'kicks', 'updated_for', existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        'poomsaes', 'created_for', existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        'poomsaes', 'updated_for', existing_type=sa.UUID(), nullable=True
    )
    op.add_column('tokens', sa.Column('created_for', sa.UUID(), nullable=True))
    op.add_column('tokens', sa.Column('updated_for', sa.UUID(), nullable=True))
    op.alter_column(
        'tokens', 'fk_user', existing_type=sa.UUID(), nullable=False
    )
    op.drop_index('idx_fk_is_invalid', table_name='tokens')
    op.drop_index('idx_fk_token', table_name='tokens')
    op.drop_index('idx_fk_user', table_name='tokens')
    op.drop_index('email_index', table_name='users')
    op.drop_index('username_index', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username_index', 'users', ['username'], unique=False)
    op.create_index('email_index', 'users', ['email'], unique=False)
    op.create_index('idx_fk_user', 'tokens', ['fk_user'], unique=False)
    op.create_index('idx_fk_token', 'tokens', ['access_token'], unique=False)
    op.create_index(
        'idx_fk_is_invalid', 'tokens', ['is_invalid'], unique=False
    )
    op.alter_column(
        'tokens', 'fk_user', existing_type=sa.UUID(), nullable=True
    )
    op.drop_column('tokens', 'updated_for')
    op.drop_column('tokens', 'created_for')
    op.alter_column(
        'poomsaes', 'updated_for', existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        'poomsaes', 'created_for', existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        'kicks', 'updated_for', existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        'kicks', 'created_for', existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        'kibon_donjaks', 'updated_for', existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        'kibon_donjaks', 'created_for', existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        'kibon_donjaks',
        'description',
        existing_type=sa.String(length=600),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.create_index('idx_gub', 'bands', ['gub'], unique=False)
    op.create_index(
        'idx_created_updated_for',
        'bands',
        ['created_for', 'updated_for'],
        unique=False,
    )
    op.create_index(
        'idx_created_updated_at',
        'bands',
        ['created_at', 'updated_at'],
        unique=False,
    )
    op.alter_column(
        'bands', 'updated_for', existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        'bands', 'created_for', existing_type=sa.UUID(), nullable=False
    )
    op.drop_column('band_poomsae', 'updated_for')
    op.drop_column('band_poomsae', 'created_for')
    op.drop_column('band_poomsae', 'updated_at')
    op.drop_column('band_poomsae', 'created_at')
    op.drop_column('band_poomsae', 'id')
    op.drop_column('band_kick', 'updated_for')
    op.drop_column('band_kick', 'created_for')
    op.drop_column('band_kick', 'updated_at')
    op.drop_column('band_kick', 'created_at')
    op.drop_column('band_kick', 'id')
    op.drop_table('band_kibon_donjak')
    # ### end Alembic commands ###
